version: '3.8'

services:
  adonis:
    build: .
    container_name: adonisjs-app
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    environment:
      - DB_MARIADB_HOST=mariadb
      - DB_MARIADB_PORT=3306
      - DB_MARIADB_USER=root
      - DB_MARIADB_PASSWORD=example
      - DB_MARIADB_DATABASE=adonis_mariadb_db
      - DB_POSTGRES_HOST=postgresql
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_USER=postgres
      - DB_POSTGRES_PASSWORD=example
      - DB_POSTGRES_DATABASE=adonis_postgres_db
    depends_on:
      - mariadb
      - postgresql
    networks:
      - backend

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: adonis_mariadb_db
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 172.18.0.3  # Direcci칩n IP est치tica para MariaDB

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: adonis_postgres_db
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 172.18.0.2  # Direcci칩n IP est치tica para PostgreSQL

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/16"  # Definir la subred para la red backend
